enum BrandType {
  // barnadName(BrandTitle, backendName, ['models'], ['car', 'motor_bike', 'water_craft', 'van', 'bus', 'lorry', 'quad_bike', '3_wheeler','taxi','rv_campervan'])
  all('All', 'all', <String>[
    'model1',
    'model 2'
  ], <String>[
    'car',
    'motor_bike',
    'water_craft',
    'van',
    'bus',
    'lorry',
    'quad_bike',
    '3_wheeler',
    'taxi',
    'rv_campervan',
  ]),
  abarth(
    'Abarth',
    'abarth',
    <String>[
      '500',
      '500 EsseEsse',
      '500C',
      '500tf',
      '595',
      'Grande Punto',
      'Grande Punto EsseEsse',
      'Punto Evo',
      'Punto Evo EsseEsse',
      'CDX',
      'CL',
      'EL',
      'ILX',
      'Integra',
      'MDX',
      'NSX',
      'RDX',
      'RL',
      'RLX',
      'RSX',
      'TL',
      'TLX',
      'TLX-L',
      'TSX',
      'ZDX',
      'Other',
    ],
    <String>[],
  ),
  alfaRomeo(
    'Alfa Romeo',
    'alfa_romeo',
    <String>[
      '145',
      '146',
      '147',
      '156',
      '159',
      '166',
      '4C',
      '8C Competizione',
      'Brera',
      'Giulietta',
      'GT',
      'GTV',
      'MiTo',
      'Spider',
      'Stelvio',
      'Tonale',
      'Other',
    ],
    <String>[],
  ),
  astonMartin(
    'Aston Martin',
    'aston_martin',
    <String>[
      'Cygnet',
      'DBS',
      'DB9',
      'DB11',
      'DBS Superleggera',
      'DBS Violante',
      'DBX',
      'Rapide',
      'V12 Vanquish',
      'V12 Vantage',
      'Vantage Roadster',
      'V8 Vantage',
      'Valkyrie',
      'Vanquish',
      'Vantage',
      'Virage',
      'Zagato Coupe',
      'Other',
    ],
    <String>[],
  ),
  audi(
    'Audi',
    'audi',
    <String>[
      'A1',
      'A1 Allstreet',
      'A1 Citycarver',
      'A2',
      'A3',
      'A4',
      'A4 Allroad Quattro',
      'A5',
      'A6',
      'A7',
      'A8',
      'Allroad',
      'e-tron',
      'e-tron GT',
      'e-tron S',
      'e-tron S Sportback',
      'e-tron Sportback',
      'Q2',
      'Q2L',
      'Q3',
      'Q3 Sportback',
      'Q3 RS',
      'Q4',
      'Q4 Sportback',
      'Q5',
      'Q5 Sportback',
      'Q6',
      'Q7',
      'Q8',
      'Q8 e-tron',
      'R8',
      'RS e-tron GT',
      'RS Q3',
      'RS Q3 Sportback',
      'RS Q7',
      'RS Q8',
      'RS3',
      'RS4',
      'RS5',
      'RS6',
      'RS7',
      'S1',
      'S3',
      'S4',
      'S5',
      'S6',
      'S7',
      'S8',
      'SQ2',
      'SQ5',
      'SQ5 Sportback',
      'SQ7',
      'SQ8',
      'SQ8 e-tron',
      'SQ8 Sportback e-tron',
      'TT',
      'TT RS',
      'TTS',
      'Other',
    ],
    <String>[],
  ),
  bentley(
    'Bentley',
    'bentley',
    <String>[
      'Arnage',
      'Azure',
      'Bentayga',
      'Brooklands',
      'Continental',
      'Continental Flying Spur',
      'Continental GT',
      'Continental GTC',
      'Flying Spur',
      'Mulsanne',
      'Other',
    ],
    <String>[],
  ),
  bmw(
    'BMW',
    'bmw',
    <String>[
      '1 series',
      '2 series',
      '3 series',
      '4 series',
      '5 series',
      '6 series',
      '7 series',
      '8 series',
      'i3',
      'i4',
      'i7',
      'i8',
      'iX',
      'iX1',
      'iX3',
      'M2',
      'M3',
      'M4',
      'M5',
      'M6',
      'M8',
      'X1',
      'X2',
      'X3',
      'X3 M',
      'X4',
      'X4 M',
      'X5',
      'X5 M',
      'X6',
      'X6 M',
      'X7',
      'XM',
      'Z3',
      'Z4',
      'Z8',
      'Other',
    ],
    <String>[],
  ),
  brilliance(
    'Brilliance',
    'brilliance',
    <String>[
      'Galena',
      'Jinbei',
      'M1',
      'H230',
      'V3',
      'V5',
      'Other',
    ],
    <String>[],
  ),
  bugatti(
    'Bugatti',
    'bugatti',
    <String>[
      'Chiron',
      'Divo',
      'Veyron',
      'Century',
      'Other',
    ],
    <String>[],
  ), // NEW
  buick(
    'Buick',
    'buick',
    <String>[
      'Century',
      'Electra',
      'Enclave',
      'Encore',
      'Envision',
      'Estate Wagon',
      'GL8 ES',
      'La Crosse',
      'Le Sabre',
      'Lucerne',
      'Park Avenue',
      'Rainier',
      'Reatta',
      'Regal',
      'Rendezvous',
      'Riviera',
      'Roadmaster',
      'Skylark',
      'Terraza',
      'Verano',
      'Other',
    ],
    <String>[],
  ), // NEW
  byd(
    'BYD',
    'byd',
    <String>[
      'Qin',
      'Other',
    ],
    <String>[],
  ),
  cadillac(
    'Cadillac',
    'cadillac',
    <String>[
      'ATS',
      'ATS-V',
      'BLS',
      'CT4',
      'CT4-V',
      'CT5',
      'CT5-V',
      'CT6',
      'CTS',
      'De Ville',
      'DTS',
      'Eldorado',
      'ELR',
      'Escalade',
      'Lyriq',
      'Seville',
      'SRX',
      'STS',
      'XLR',
      'XT4',
      'XT5',
      'XT6',
      'XTS',
      'Other',
    ],
    <String>[],
  ),
  changan(
    'Changan',
    'changan',
    <String>[
      'Alsvin',
      'CS35',
      'CS35 Plus',
      'CS55',
      'CS55 Plus',
      'CS75',
      'CS75 Plus',
      'CS85 Coupe',
      'CS95',
      'Eado',
      'Eado Plus',
      'Raeton',
      'Raeton CC',
      'Raeton Plus',
      'Uni-K',
      'Uni-T',
      'Uni-V',
      'Other',
    ],
    <String>[],
  ),
  chery(
    'Chery',
    'chery',
    <String>[
      'Amulet',
      'Arrizo 5 Plus',
      'Arrizo 6',
      'Arrizo 6 Pro',
      'Arrizo 7',
      'Arrizo 8',
      'Bonus',
      'Bonus 3',
      'CrossEastar',
      'Eastar',
      'eQ',
      'eQ1',
      'eQ5',
      'Fora',
      'iCar',
      'IndiS',
      'Kimo',
      'M11',
      'Omoda 5',
      'QQ',
      'QQ3',
      'QQ6',
      'Tiggo',
      'Tiggo 2',
      'Tiggo 2 Pro',
      'Tiggo 3',
      'Tiggo 4',
      'Tiggo 4 Pro',
      'Tiggo 5',
      'Tiggo 7',
      'Tiggo 7 Pro',
      'Tiggo 8',
      'Tiggo 8 Plus',
      'Tiggo 8 Pro',
      'Tiggo 8 Pro Max',
      'Tiggo e',
      'Very',
      'Other',
    ],
    <String>[],
  ),
  chevrolet(
    'Chevrolet',
    'chevrolet',
    <String>[
      'Agile',
      'Astro',
      'Astra',
      'Avalanchex',
      'Aveo',
      'Beat',
      'Blazer',
      'Bolt',
      'Bolt EUV',
      'Camaro',
      'Captiva',
      'Celta',
      'Cobalt',
      'Colorado',
      'Classic',
      'Cobalt',
      'Colorado',
      'Corvette',
      'Corsa',
      'Cruze',
      'Epica',
      'Equinox',
      'Express',
      'HHR',
      'Impala',
      'Lacetti',
      'Lanos',
      'Malibu',
      'Monte Carlo',
      'Meriva',
      'Montana',
      'Niva',
      'Orlando',
      'Rezzo',
      'Prisma',
      'Silverado',
      'Silverado 1500',
      'Silverado 2500 HD',
      'Silverado HD',
      'Sonic',
      'Spark',
      'SSR',
      'Suburban',
      'Tornado',
      'Tahoe',
      'TrailBlazer',
      'Traverse',
      'Trax',
      'Uplander',
      'Venture',
      'Vectra',
      'Zafira',
      'Other',
    ],
    <String>[],
  ),
  chrysler(
    'Chrysler',
    'chrysler',
    <String>[
      '200',
      '300',
      '300 M',
      '300 C',
      'Concorde',
      'Crossfire',
      'Grand Caravan',
      'Grand Voyager',
      'Pacifica',
      'Pt Cruiser',
      'Sebring',
      'Town & Country',
      'Voyager',
      'Other',
    ],
    <String>[],
  ),
  citroen(
    'Citroen',
    'citroen',
    <String>[
      'Berlingo',
      'C-Crosser',
      'C-Elysee',
      'C1',
      'C2',
      'C3',
      'C3 Aircross',
      'C3 Picasso',
      'C3 Pluriel',
      'C4',
      'C4 Aircross',
      'C4 Cactus',
      'C4 Picasso',
      'C4 Coupe',
      'C4 Grand Picasso',
      'C4 Space Tourer',
      'C4 X',
      'C5',
      'C5 Aircross',
      'C6',
      'C8',
      'C-Crosser',
      'DS 7 Crossback',
      'DS3',
      'DS4',
      'DS5',
      'Evasion',
      'Grand C4 Picasso',
      'Grand C4 SpaceTourer',
      'Jumper',
      'Jumpy',
      'Nemo',
      'Saxo',
      'Spacetourer',
      'Xantia',
      'Xsara',
      'Xsara Picasso',
      'Other',
    ],
    <String>[],
  ),
  dacia(
    'Dacia',
    'dacia',
    <String>[
      'Dokker',
      'Duster',
      'Lodgy',
      'Logan',
      'Logan MCV',
      'Logan Pick-Up',
      'Sandero',
      'Sandero Stepway',
      'Solenza',
      'Spring',
      'SupeRNova',
      'Other',
    ],
    <String>[],
  ),
  daewoo(
    'Daewoo',
    'daewoo',
    <String>[
      'Evanda',
      'Kalos',
      'Leganza',
      'Magnus',
      'Matiz',
      'Nexia',
      'Nubira',
      'Other',
    ],
    <String>[],
  ),
  daihatsu(
    'Daihatsu',
    'daihatsu',
    <String>[
      'Applause',
      'Cast',
      'Copen',
      'Cuore',
      'Gran Move',
      'Luxio',
      'Materia',
      'Mebius',
      'Move',
      'Rocky',
      'Sirion',
      'Terios',
      'Trevis',
      'YRV',
      'Other',
    ],
    <String>[],
  ),
  datsun(
    'Datsun',
    'datsun',
    <String>[
      'Go',
      'Go+',
      'Mi-Do',
      'On-Do',
      'Redi-Go',
      'Other',
    ],
    <String>[],
  ),
  dodge(
    'Dodge',
    'dodge',
    <String>[
      'Avenger',
      'Caliber',
      'Caliber SRT4',
      'Caravan',
      'Challenger',
      'Charger',
      'Challenger III',
      'Dakota',
      'Dart',
      'Durango',
      'Hornet',
      'Intrepid',
      'Journey',
      'Magnum',
      'Neon',
      'Nitro',
      'Ram 1500',
      'Ram 2500',
      'Ram 3500',
      'Ram SRT10',
      'Stratus',
      'Viper',
      'Other',
    ],
    <String>[],
  ),
  dongfeng(
    'Dongfeng',
    'dongfeng',
    <String>[
      '580',
      'A30',
      'Aeolus AX7',
      'AX7',
      'H30 Cross',
      'Other',
    ],
    <String>[],
  ),
  donkervoort(
      'Donkervoort', 'donkervoort', <String>['D8 GT', 'Other'], <String>[]),
  exeed('Exeed', 'exeed', <String>['TXL', 'VX', 'Other'], <String>[]),
  effedi('Effedi', 'effedi', <String>['Gasolone', 'Other'], <String>[]), // NEW
  faw(
    'FAW',
    'faw',
    <String>[
      'Bestune T77',
      'Bestune T99',
      'Besturn B30',
      'Besturn B50',
      'Besturn B70',
      'Besturn X40',
      'Besturn X80',
      'Oley',
      'Vita',
      'Other',
    ],
    <String>[],
  ),
  ferrari(
    'Ferrari',
    'ferrari',
    <String>[
      '296',
      '348',
      '360',
      '430 Scuderia',
      '456',
      '458',
      '488',
      '512',
      '550',
      '575 M',
      '575M Maranello',
      '599',
      '599 GTB Fiorano',
      '599 GTO',
      '612',
      '812',
      'California',
      'California T',
      'Challenge Stradale',
      'Enzo Ferrari',
      'F430',
      'FF',
      'SA Aperta',
      'Scuderia Spider 16M',
      'Superamerica',
      'Other',
    ],
    <String>[],
  ),
  fiat(
    'Fiat',
    'fiat',
    <String>[
      '124 Spider',
      '500',
      '500 C',
      '500 L',
      '500 X',
      'Albea',
      'Brava',
      'Bravo',
      'Coupe',
      'Croma',
      'Doblo',
      'Ducato',
      'E-Doblo',
      'E-Ulysse',
      'Egea',
      'Fiorino',
      'Freemont',
      'Grande Punto',
      'Idea',
      'Linea',
      'Marea',
      'Mille',
      'Multipla',
      'Ottimo',
      'Palio',
      'Panda',
      'Punto',
      'Punto Evo',
      'Panda 4x4',
      'Panda Cross',
      'Pulse',
      'Punto',
      'Qubo',
      'Scudo',
      'Sedici',
      'Seicento',
      'Siena',
      'Stilo',
      'Strada',
      'Tipo',
      'Ulysse',
      'Uno',
      'Viaggio',
      'Other',
    ],
    <String>[],
  ),
  fisker('Fisker', 'fisker', <String>['Karma', 'Other'], <String>[]),
  ford(
    'Ford',
    'ford',
    <String>[
      'Bantam',
      'B-Max',
      'Bronco',
      'Bronco Sport',
      'C-Max',
      'Cougar',
      'Contour',
      'Cougar',
      'Courier',
      'Crown Victoria',
      'EcoSport',
      'Endeavour',
      'Escape',
      'Escort IV',
      'E-series',
      'Esplorer',
      'Everest',
      'Excursion',
      'Expedition',
      'Explorer',
      'F-150',
      'F-250',
      'F-350',
      'F-450',
      'Fiesta',
      'Focus',
      'Focus RS',
      'Focus ST',
      'Freda',
      'Fusion',
      'Galaxy',
      'Ka',
      'Kuga',
      'Maverick',
      'Mondeo',
      'Mondeo ST',
      'Mustang',
      'Puma',
      'Puma ST',
      'Ranger',
      'S-Max',
      'S-Max +',
      'Taurus',
      'Thunderbird',
      'Transit',
      'Transit Connect',
      'Transit Tourneo',
      'Windstar',
      'Edge',
      'Endura',
      'Equator',
      'Escape',
      'Excursion',
      'Expedition',
      'Explorer',
      'Explorer Sport Trac',
      'F-150',
      'F-150 Lightning',
      'F-250',
      'F-350',
      'Falcon',
      'Fiesta',
      'Fiesta Active',
      'Five Hundred',
      'Flex',
      'Focus',
      'Focus Active',
      'Focus Electric',
      'Freestar',
      'Freestyle',
      'Fusion',
      'Galaxy',
      'Ka',
      'Kuga',
      'Maverick',
      'Mondeo',
      'Mustang',
      'Mustang Mach-E',
      'Mustang Shelby GT350',
      'Mustang Shelby GT500',
      'Puma',
      'Ranger',
      'S-Max',
      'Taurus',
      'Taurus X',
      'Thunderbird',
      'Tourneo Connect',
      'Transit',
      'Transit Connect',
      'Other',
    ],
    <String>[],
  ),
  foton('Foton', 'foton', <String>['Sauvana', 'Other'], <String>[]),
  gac(
    'GAC',
    'gac',
    <String>[
      'GM8',
      'GS5',
      'GS8',
      '3102',
      '31105',
      'Gazelle',
      'Gazelle Business',
      'Gazelle Next',
      'Gazelle NN',
      'Gazelle Sity',
      'Siber',
      'Sobol',
      'Other',
    ],
    <String>[],
  ),
  geely(
    'Geely',
    'geely',
    <String>[
      'Atlas',
      'Atlas Pro',
      'Azkarra',
      'Coolray',
      'Emgrand 7',
      'Emgrand EC7',
      'Emgrand GS',
      'Emgrand GSe',
      'Emgrand X7',
      'GC9',
      'GÐ¡6',
      'MK',
      'Monjaro',
      'Otaka',
      'Preface',
      'Tugella',
      'Vision',
      'Other',
    ],
    <String>[],
  ),
  genesis(
    'Genesis',
    'genesis',
    <String>[
      'G70',
      'G80',
      'G90',
      'GV60',
      'GV70',
      'GV80',
      'Other',
    ],
    <String>[],
  ),
  gmc(
    'GMC',
    'gmc',
    <String>[
      'C7500',
      'Sierra',
      'Tracker',
      'Envoy',
      'jimmy',
      'terrain',
      'Acadia',
      'Canyon',
      'Hover 5',
      'Hower',
      'Steed',
      'Steed 5',
      'V200',
      'Wingle Pick-Up',
      'X200',
      'Acadia',
      'Canyon',
      'Envoy',
      'Sierra 1500',
      'Sierra 2500',
      'Sierra 3500',
      'Terrain',
      'Yukon',
      'Other',
    ],
    <String>[],
  ),
  greatWall(
    'Great Wall',
    'great_wall',
    <String>[
      'Cowry',
      'Deer',
      'Hover',
      'Hover M2',
      'Pegasus',
      'Peri',
      'Poer',
      'Poer King Kong',
      'Safe',
      'Sailor',
      'Sing',
      'Socool',
      'Wingle',
      'Wingle 7',
      'Other',
    ],
    <String>[],
  ),
  haval(
    'Haval',
    'haval',
    <String>[
      'Cool Dog',
      'Dargo',
      'F7',
      'F7x',
      'H4',
      'H6',
      'H9',
      'Jolion',
      'M6 Plus',
      'Other',
    ],
    <String>[],
  ),
  honda(
    'Honda',
    'honda',
    <String>[
      'Accord',
      'Civic',
      'Civic Type S',
      'Crossroad',
      'CR-V',
      'Fr-v',
      'Hr-v',
      'S2000',
      'Other',
    ],
    <String>[],
  ),
  holden(
    'Holden',
    'holden',
    <String>[
      'Accord',
      'Amaze',
      'Agila',
      'Astra',
      'Barina',
      'Captiva',
      'Colorado',
      'Commodore',
      'Corvette C8',
      'Commodore VZ',
      'Corsa',
      'Cruze',
      'Epica',
      'Lacetti',
      'Signum',
      'Vectra',
      'Viva',
      'Zafira',
      'City',
      'Civic',
      'Civic Type R',
      'CR-V',
      'CR-Z',
      'Crosstour',
      'e',
      'Edix',
      'Element',
      'Fit',
      'FR-V',
      'HR-V',
      'Insight',
      'Jade',
      'Jazz',
      'Legend',
      'Odyssey',
      'Passport',
      'Pilot',
      'Prelude',
      'Ridgeline',
      'S2000',
      'Shuttle',
      'Stepwgn',
      'Stream',
      'Vezel',
      'Other',
    ],
    <String>[],
  ),
  hummer(
    'Hummer',
    'hummer',
    <String>[
      'H1',
      'H2',
      'H3',
      'Other',
    ],
    <String>[],
  ),
  hyundai(
    'Hyundai',
    'hyundai',
    <String>[
      'Accent',
      'Avante',
      'Azera',
      'Elantra',
      'Galloper',
      'Genesis Coupè',
      'Getz',
      'Grandeur',
      'Grandeur TG',
      'H1',
      'H200',
      'I20',
      'I30',
      'I55',
      'IX20',
      'ix35',
      'Lavita',
      'Matrix',
      'Santa Fe',
      'Sonata',
      'Starex',
      'Terracan',
      'Trajet',
      'Tucson',
      'Veloster',
      'Veloster Turbo',
      'Veracruz',
      'Verna',
      'Accent',
      'Atos Prime',
      'Azera',
      'Bayon',
      'Centennial',
      'Creta',
      'Creta Grand',
      'Elantra',
      'Entourage',
      'Eon',
      'Equus',
      'Galloper',
      'Genesis',
      'Genesis Coupe',
      'Getz',
      'Grandeur',
      'H-1',
      'i10',
      'i20',
      'i20 N',
      'i30',
      'i30 N',
      'i40',
      'Ioniq',
      'Ioniq 5',
      'Ioniq 6',
      'ix20',
      'ix35',
      'Kona',
      'Kona N',
      'Kusto',
      'Matrix',
      'Mistra',
      'Nexo',
      'Palisade',
      'Porter',
      'Santa Cruz',
      'Santa Fe',
      'Solaris',
      'Sonata',
      'Staria',
      'Terracan',
      'Trajet',
      'Tucson',
      'Veloster',
      'Venue',
      'Veracruz',
      'Verna',
      'Xcent',
      'XG',
      'Other',
    ],
    <String>[],
  ),
  infiniti(
    'Infiniti',
    'infiniti',
    <String>[
      'Fx25',
      'FX30d',
      'Fx35',
      'FX37',
      'M35h',
      'M56',
      'Q50',
      'QX56',
      'QX70',
      'EX',
      'FX',
      'G',
      'I35',
      'JX',
      'M',
      'Q30',
      'Q40',
      'Q45',
      'Q50',
      'Q60',
      'Q70',
      'QX30',
      'QX4',
      'QX50',
      'QX55',
      'QX56',
      'QX60',
      'QX70',
      'QX80',
      'Other',
    ],
    <String>[],
  ),
  isuzu(
    'Isuzu',
    'isuzu',
    <String>[
      'D-Max',
      'Forward',
      'Mu-X',
      'N series',
      'Pick-Up',
      'Ascender',
      'Axiom',
      'D-Max',
      'D-Max Rodeo',
      'I280',
      'I290',
      'I350',
      'I370',
      'mu-X',
      'Rodeo',
      'Trooper',
      'VehiCross',
      'Other',
    ],
    <String>[],
  ),
  iveco('Iveco', 'iveco', <String>['Daily'], <String>[]),
  jac(
    'JAC',
    'jac',
    <String>[
      'iEV7S',
      'J7',
      'JS3',
      'JS4',
      'JS6',
      'T6',
      'Other',
    ],
    <String>[],
  ),
  jaguar(
    'Jaguar',
    'jaguar',
    <String>[
      'E-Pace',
      'F-Type',
      'F-Type',
      'I-Pace',
      'S-type',
      'X-Type',
      'XE',
      'XF',
      'XK/XKR',
      'XFR',
      'XJ',
      'Xk',
      'Xk8',
      'X-type',
      'Other',
    ],
    <String>[],
  ),
  jeep(
    'Jeep',
    'jeep',
    <String>[
      'Cherokee',
      'Commander',
      'Compass',
      'Gladiator',
      'Grand Cherokee',
      'Grand Wagoneer',
      'Liberty',
      'Meridian',
      'Patriot',
      'Renegade',
      'Wagoneer',
      'Wrangler',
      'Other',
    ],
    <String>[],
  ),
  jmc(
    'JMC (Jiangling Motors Corporation)',
    'jmc',
    <String>['New Generation Transit', 'Other'],
    <String>[],
  ),
  kia(
    'Kia',
    'kia',
    <String>[
      'Bongo',
      'Borrego',
      'Carens',
      'Carnival',
      'Ceed',
      'Ceed GT',
      'Cerato',
      'Forte',
      'Magentis',
      'Mohave',
      'Morning',
      'Opirus',
      'Optima',
      'Picanto',
      'Rio',
      'Sedona',
      'Sorento',
      'Soul',
      'Sportage',
      'Venga',
      'Clarus',
      'EV6',
      'Forte',
      'K5',
      'K8',
      'K900',
      'Niro',
      'Opirus',
      'ProCeed',
      'Quoris',
      'Ray',
      'Rio',
      'Rio X',
      'Rio X-Line',
      'Seltos',
      'Shuma',
      'Sonet',
      'Sorento',
      'Sorento Prime',
      'Soul',
      'Spectra',
      'Stinger',
      'Stonic',
      'Telluride',
      'Venga',
      'XCeed',
      'Other',
    ],
    <String>[],
  ),
  ktm('KTM', 'ktm', <String>['X-Bow', 'Other'], <String>[]),
  lamborghini(
    'Lamborghini',
    'lamborghini',
    <String>[
      'Gallardo',
      'Hurracan',
      'Aventador',
      'Aventador',
      'Centenario',
      'Diablo',
      'Gallardo',
      'Huracan',
      'Murcielago',
      'Reventon',
      'Sian',
      'Urus',
      'Other',
    ],
    <String>[],
  ),
  lancia(
    'Lancia',
    'lancia',
    <String>[
      'Delta',
      'K',
      'Lybra',
      'Musa',
      'New Ypsilon',
      'Phedra',
      'Thema',
      'Thesis',
      'Voyager',
      'Y',
      'Ypsilon',
      'Z',
      'Other',
    ],
    <String>[],
  ),
  landRover(
    'Land Rover',
    'land_rover',
    <String>[
      'Defender',
      'Discovery',
      'Discovery Sport',
      'Evoque',
      'Freelander',
      'Range Rover',
      'Range Rover Evoque',
      'Range Rover Sport',
      'Other',
    ],
    <String>[],
  ),
  lexus(
    'Lexus',
    'lexus',
    <String>[
      'GS 300',
      'IS 220d',
      'IS-F',
      'Elise',
      'Europa',
      'Evora',
      'Exige',
      'CT',
      'ES',
      'GS',
      'GX',
      'HS',
      'IS',
      'LC',
      'LFA',
      'LM',
      'LS',
      'LX',
      'NX',
      'RC',
      'RC F',
      'RX',
      'SC',
      'UX',
      'Other',
    ],
    <String>[],
  ),
  lifan(
    'Lifan',
    'lifan',
    <String>[
      'Breez',
      'Cebrium',
      'Celliya',
      'Murman',
      'Myway',
      'Smily',
      'Solano',
      'X50',
      'X60',
      'X70',
      'X80',
      'Other',
    ],
    <String>[],
  ),
  lincoln(
    'Lincoln',
    'lincoln',
    <String>[
      'Aviator',
      'Corsair',
      'Mark LT',
      'MKC',
      'MKS',
      'MKT',
      'MKX',
      'MKZ',
      'Nautilus',
      'Navigator',
      'Town Car',
      'Zephyr',
      'Other',
    ],
    <String>[],
  ),
  lotus(
    'Lotus',
    'lotus',
    <String>[
      'Elise',
      'Emira',
      'Europa S',
      'Evora',
      'Exige',
      'Other',
    ],
    <String>[],
  ),
  lti('LTI Vehicles', 'lti', <String>['TX4', 'Other'], <String>[]), // NEW
  luxgen('Luxgen', 'luxgen', <String>['Luxgen 7', 'Other'], <String>[]),
  marussia('Marussia', 'marussia', <String>['B1', 'B2', 'Other'], <String>[]),
  mahindra(
    'Mahindra',
    'mahindra',
    <String>[
      'Goa',
      'Meagle',
      'Pick-Up',
      'Scorpio',
      'Thar',
      'XUV500',
      'Xylo',
      'Other',
    ],
    <String>[],
  ),
  maruti('Maruti', 'maruti', <String>['Ritz', 'Other'], <String>[]),
  maserati('Maserati', 'maserati', <String>[
    'Ghibli III',
    'Granturismo S',
    'Quattroporte',
    '3200 GT',
    'Ghibli',
    'Gran Cabrio',
    'Gran Turismo ',
    'Gran Turismo S',
    'Grecale',
    'Levante',
    'MC20',
    'Quattroporte',
    'Quattroporte S',
    'Other'
  ], <String>[]),
  mazda(
    'Mazda',
    'mazda',
    <String>[
      '2',
      '2 Hybrid',
      '323',
      '3',
      '5',
      '6',
      'Atenza',
      'Axela',
      'Bongo',
      'BT2500',
      'BT-50',
      'CX-5',
      'CX-7',
      'Demio',
      'MX-5',
      'Protege',
      'RX-8',
      'Tribute',
      '626',
      'B-Series',
      'BT-50',
      'CX-3',
      'CX-30',
      'CX-30 EV',
      'CX-4',
      'CX-5',
      'CX-50',
      'CX-60',
      'CX-7',
      'CX-8',
      'CX-9',
      'MPV',
      'MX-30',
      'MX-5',
      'Premacy',
      'RX-7',
      'RX-8',
      'Tribute',
      'Other',
    ],
    <String>[],
  ),
  maybach(
    'Maybach',
    'maybach',
    <String>[
      '57',
      '57 S',
      '62',
      '62 S',
      'Landaulet',
      'Other',
    ],
    <String>[],
  ),
  mcLaren(
    'McLaren',
    'mc_laren',
    <String>[
      '540C',
      '570S',
      '600LT',
      '650S',
      '675LT',
      '720S',
      '720S Spider',
      '765LT',
      'Artura',
      'MP4-12C',
      'P1',
      'Other',
    ],
    <String>[],
  ),
  mercedes(
    'Mercedes',
    'mercedes',
    <String>[
      'A',
      'B',
      'C',
      'Citan',
      'Cl',
      'Cla',
      'Clc',
      'Clk',
      'Cls',
      'E',
      'G',
      'Gl',
      'GLA',
      'Glk',
      'M',
      'ML',
      'R',
      'S',
      'Sl',
      'Slk',
      'Sls',
      'SportCoupe',
      'Sprinter',
      'V',
      'Vaneo',
      'Viano',
      'Vito',
      'A-class',
      'AMG GT',
      'AMG GT 4-Door',
      'B-class',
      'C-class',
      'C-class Sport Coupe',
      'Citan',
      'CL-class',
      'CLA-class',
      'CLC-class ',
      'CLK-class',
      'CLS-class',
      'E-class',
      'E-class Coupe',
      'EQA',
      'EQB',
      'EQC',
      'EQE',
      'EQE AMG',
      'EQS',
      'EQS AMG',
      'EQT',
      'EQV',
      'G-class',
      'GL-class',
      'GLA-class',
      'GLA-class AMG',
      'GLB-class',
      'GLC-class',
      'GLC-class AMG',
      'GLC-class Coupe',
      'GLE-class',
      'GLE-class AMG',
      'GLE-class Coupe',
      'GLK-class',
      'GLS-class',
      'GLS-class AMG',
      'M-class',
      'R-class',
      'S-class',
      'S-class Cabrio',
      'S-class Coupe',
      'SL-class',
      'SL-Class AMG',
      'SLC-class',
      'SLK-class',
      'SLR-class',
      'SLS AMG',
      'X-class',
      'Other',
    ],
    <String>[],
  ),
  mercury(
    'Mercury',
    'mercury',
    <String>[
      'Grand Marquis',
      'Mariner',
      'Milan',
      'Montego',
      'Monterey',
      'Mountaineer',
      'Sable',
      'Other',
    ],
    <String>[],
  ),
  mg(
    'MG',
    'mg',
    <String>[
      '4',
      'Hector',
      'TF',
      'VS',
      'XPower SV',
      'ZR',
      'ZS',
      'ZS EV',
      'ZT',
      'ZT-T',
      'Other',
    ],
    <String>[],
  ),
  mini(
    'Mini',
    'mini',
    <String>[
      'Clubman',
      'Clubman S',
      'Clubvan',
      'Cooper',
      'Cooper Cabrio',
      'Cooper S',
      'Cooper S Cabrio',
      'Cooper S Countryman All4',
      'Countryman',
      'One',
      'Other',
    ],
    <String>[],
  ),
  mitsubishi(
    'Mitsubishi',
    'mitsubishi',
    <String>[
      'Adventure',
      'Airtek',
      'Asx',
      'Carisma',
      'Challenger',
      'Chariot',
      'Colt',
      'Delica',
      'Diamante',
      'Dion',
      'Eclipse',
      'Freeca',
      'Fuzion',
      'Galant',
      'Grandis',
      'Grunder',
      'L200',
      'Lancer',
      'Lancer Evolution',
      'Lancer Evolution T.M.E.',
      'Montero',
      'Montero Sport',
      'Nativa',
      'Nimbus',
      'Outlander',
      'Pajero',
      'Pajero Pinin',
      'Pajero Sport',
      'Rvr',
      'Shogun Sport',
      'Space Runner',
      'Space Star',
      'Triton',
      'Fuso	Canter',
      'Fuso	Fighter',
      '3000 GT',
      'ASX',
      'Carisma',
      'Colt',
      'Dignity',
      'Eclipse',
      'Eclipse Cross',
      'Endeavor',
      'Galant',
      'Grandis',
      'i-MiEV',
      'L200',
      'Lancer',
      'Lancer Evo',
      'Mirage',
      'Outlander',
      'Outlander Sport',
      'Outlander XL',
      'Pajero',
      'Pajero Pinin',
      'Pajero Sport',
      'Raider',
      'Space Gear',
      'Space Runner',
      'Space Star',
      'Xpander',
      'Other',
    ],
    <String>[],
  ),
  moskvich('Moskvich', 'moskvich', <String>['3E', 'Other'], <String>[]),
  mitsubishiFuse(
    'Mitsubishi Fuso',
    'mitsubishi_fuso',
    <String>[
      'Canter',
      'Fighter',
      'Other',
    ],
    <String>[],
  ),
  nissan(
    'Nissan',
    'nissan',
    <String>[
      '350z',
      '370z',
      'Almera',
      'Almera Classic',
      'Atleon',
      'Avenir',
      'Cabstar',
      'Cabstar E',
      'Cube',
      'Frontier',
      'Gt-r',
      'Interstar',
      'Juke',
      'Kubistar',
      'Lp300',
      'Maxima',
      'Micra',
      'Murano',
      'Navara',
      'Note',
      'Np300',
      'Nv 200',
      'NV 400',
      'Pathfinder',
      'Patrol',
      'Presage',
      'Primastar',
      'Primera',
      'Qashqai',
      'Sentra',
      'Teana',
      'Terrano ii',
      'Tiida',
      'X-trail',
      'Almera Tino',
      'Altima',
      'Ariya',
      'Armada',
      'Bluebird Sylphy',
      'Frontier',
      'GT-R',
      'Juke',
      'Leaf',
      'Maxima',
      'Micra',
      'Murano',
      'Navara',
      'Note',
      'NP300',
      'Pathfinder',
      'Patrol',
      'Primera',
      'Qashqai',
      'Qashqai+2',
      'Quest',
      'Rogue',
      'Sentra',
      'Skyline',
      'Sylphy',
      'Teana',
      'Terrano',
      'Tiida',
      'Titan',
      'Titan XD',
      'X-Trail',
      'XTerra',
      'Z',
      'Other',
    ],
    <String>[],
  ),
  // noble('Noble', 'noble'),
  opel(
    'Opel',
    'opel',
    <String>[
      'Adam',
      'Agila',
      'Antara',
      'Astra',
      'Cascada',
      'Celta',
      'Combo',
      'Corsa',
      'Frontera',
      'GT',
      'Insignia',
      'Meriva',
      'Mokka',
      'Movano',
      'Omega',
      'Signum',
      'Sintra',
      'Speedster',
      'Tigra',
      'Vectra',
      'Vita',
      'Vivaro',
      'Zafira',
      'Ampera-e',
      'Antara',
      'Astra',
      'Astra GTC',
      'Astra OPC',
      'Cascada',
      'Combo',
      'Combo Life',
      'Corsa',
      'Corsa OPC',
      'Crossland',
      'Crossland X',
      'Frontera',
      'Grandland',
      'Grandland X',
      'Insignia',
      'Insignia OPC',
      'Karl',
      'Meriva',
      'Mokka',
      'Omega',
      'Signum',
      'Speedster',
      'Tigra',
      'Vectra',
      'Vivaro',
      'Zafira',
      'Zafira Life',
      'Zafira Tourer',
      'Other',
    ],
    <String>[],
  ),
  peugeot(
    'Peugeot',
    'peugeot',
    <String>[
      '1007',
      '106',
      '107',
      '108',
      '2008',
      '206',
      '207',
      '208',
      '3008',
      '301',
      '307',
      '308',
      '4007',
      '406',
      '407',
      '5008',
      '508',
      '607',
      '806',
      '807',
      'Bipper',
      'Boxer',
      'Expert',
      'Partner',
      'Ranch',
      'RCZ',
      'Landtrek',
      'Manager',
      'Partner',
      'Partner Crossway',
      'Partner Rapid',
      'RCZ Sport',
      'Rifter',
      'Traveller',
      'Other',
    ],
    <String>[],
  ),
  plymouth(
      'Plymouth', 'plymouth', <String>['Road Runner', 'Other'], <String>[]),
  piaggio('Piaggio', 'piaggio', <String>['Porter', 'Other'], <String>[]), // NEW
  pontiac(
    'Pontiac',
    'pontiac',
    <String>[
      'Aztec',
      'Bonneville',
      'Firebird',
      'G5 Pursuit',
      'G6',
      'G8',
      'Grand AM',
      'Grand Prix',
      'GTO',
      'Montana',
      'Solstice',
      'Sunfire',
      'Torrent',
      'Vibe',
      'Other',
    ],
    <String>[],
  ),
  porsche(
    'Porsche',
    'porsche',
    <String>[
      '718 Boxster',
      '718 Cayman',
      '911',
      '918',
      '993',
      '996',
      '997',
      'Boxster I',
      'Boxster II',
      'Boxster III',
      'Cayenne',
      'Cayman',
      'Macan',
      'Panamera',
      'Boxster',
      'Cayenne',
      'Cayman',
      'Macan',
      'Panamera',
      'Taycan',
      'Other',
    ],
    <String>[],
  ),
  ravon('Ravon', 'ravon', <String>['Gentra', 'Other'], <String>[]),
  renault(
    'Renault',
    'renault',
    <String>[
      'Avantime',
      'Captur',
      'Clio',
      'Duster',
      'Espace',
      'Fluence',
      'Grand Scenic',
      'Kadjar',
      'Kangoo',
      'Koleos',
      'Laguna',
      'Logan',
      'Logan MCV',
      'Logan Pick-Up',
      'Mascott',
      'Master',
      'Maxity',
      'Megane',
      'Modus',
      'Safrane',
      'Sandero',
      'Scenic',
      'Thalia',
      'Trafic',
      'Twingo',
      'Vel Satis',
      'Wind',
      'Alaskan',
      'Arkana',
      'Austral',
      'Avantime',
      'Duster Oroch',
      'Kaptur',
      'Kiger',
      'Koleos',
      'Latitude',
      'Logan Stepway',
      'Megane E-Tech',
      'Sandero Stepway',
      'Symbol',
      'Taliant',
      'Talisman',
      'Trafic',
      'Triber',
      'Twingo',
      'Twizy',
      'Vel Satis',
      'Wind',
      'Zoe',
      'Other',
    ],
    <String>[],
  ),
  rollsRoyce(
    'Rolls-Royce',
    'rolls_royce',
    <String>[
      'Cullinan',
      'Dawn',
      'Ghost',
      'Phantom',
      'Wraith',
      'Other',
    ],
    <String>[],
  ),
  renaultSamsung(
    'Renault Samsung',
    'renault_samsung',
    <String>[
      'SM3',
      'SM5',
      'SM7',
      'Other',
    ],
    <String>[],
  ), // NEW
  rover(
    'Rover',
    'rover',
    <String>[
      '25',
      '400',
      '45',
      '600',
      '75',
      'Streetwise',
      'Other',
    ],
    <String>[],
  ),
  // ruf('Ruf', 'ruf'),
  saab(
    'Saab',
    'saab',
    <String>[
      '9-2x',
      '45538',
      '9-4x',
      '45540',
      '9-7x',
      'Other',
    ],
    <String>[],
  ),
  saleen('Saleen', 'saleen', <String>['S7 Twin Turbo', 'Other'], <String>[]),
  saturn(
    'Saturn',
    'saturn',
    <String>[
      'Agila',
      'Astra',
      'Commodore VZ',
      'Corsa',
      'Signum',
      'Zafira',
      'Aura',
      'Ion',
      'LW',
      'Outlook',
      'Sky',
      'Vue',
      'Other',
    ],
    <String>[],
  ),
  scion(
    'Scion',
    'scion',
    <String>[
      'FR-S',
      'tC',
      'xA',
      'xB',
      'xD',
      'Other',
    ],
    <String>[],
  ),
  seat(
    'Seat',
    'seat',
    <String>[
      'Alhambra',
      'Altea',
      'Arosa',
      'Cordoba',
      'Exeo',
      'Ibiza',
      'Inca',
      'Leon',
      'Mii',
      'Toledo',
      'Altea Freetrack',
      'Altea XL',
      'Arona',
      'Arosa',
      'Ateca',
      'Cordoba',
      'Exeo',
      'Ibiza',
      'Leon',
      'Mii',
      'Tarraco',
      'Toledo',
      'Other',
    ],
    <String>[],
  ),
  skoda(
    'Skoda',
    'skoda',
    <String>[
      'Citigo',
      'Fabia',
      'Octavia',
      'Rapid',
      'Roomster',
      'Superb',
      'Yeti',
      'Enyaq iV',
      'Felicia',
      'Kamiq',
      'Karoq',
      'Kodiaq',
      'Octavia Scout',
      'Octavia Tour',
      'Praktik',
      'Rapid',
      'Rapid Spaceback (NH1)',
      'Roomster',
      'Scala',
      'Other',
    ],
    <String>[],
  ), // NEW
  smart(
    'Smart',
    'smart',
    <String>[
      '#1',
      'Forfour',
      'Fortwo',
      'Fortwo Brabus',
      'Roadster',
      'Roadster Brabus',
      'Other',
    ],
    <String>[],
  ), // NEW
  ssangYong(
    'SsangYong',
    'ssang_yong',
    <String>[
      'Actyon',
      'Actyon Sports',
      'Korando',
      'Kyron',
      'Rexton',
      'Rodius',
      'Chairman',
      'LUVi',
      'Musso',
      'Musso Grand',
      'Musso Sport',
      'Rexton Sports',
      'Stavic',
      'Tivoli',
      'Tivoli Grand',
      'XLV',
      'Other',
    ],
    <String>[],
  ),
  subaru(
    'Subaru',
    'subaru',
    <String>[
      'BRZ',
      'Forester',
      'Forester (S13)',
      'Forester (SJ)',
      'Impreza',
      'Legacy',
      'Outback',
      'Traviq',
      'Tribeca',
      'XV',
      'Ascent',
      'Baja',
      'BRZ',
      'Crosstrack',
      'Exiga',
      'Forester',
      'Impreza',
      'Impreza WRX',
      'Impreza WRX STI',
      'Justy',
      'Legacy',
      'Levorg',
      'Outback',
      'Solterra',
      'Traviq',
      'Tribeca',
      'WRX',
      'XV',
      'Other',
    ],
    <String>[],
  ),
  suzuki(
    'Suzuki',
    'suzuki',
    <String>[
      'Forenza',
      'Fun',
      'Grand Vitara',
      'Ignis',
      'Jimny',
      'Kizashi',
      'Reno',
      'S-Cross',
      'Splash',
      'Swift',
      'Sx4',
      'Vitara',
      'Wagon R+',
      'WagonR',
      'XL7',
      'Alto',
      'Baleno',
      'Celerio',
      'Ciaz',
      'Ertiga',
      'Grand Vitara',
      'Grand Vitara XL7',
      'Ignis',
      'Jimny',
      'Kizashi',
      'Liana',
      'S-Presso',
      'Splash',
      'Swift',
      'SX4',
      'Vitara',
      'Wagon R',
      'Wagon R+',
      'XL6',
      'XL7',
      'Other',
    ],
    <String>[],
  ),
  tataMotors(
    'Tata Motors',
    'tata_motors',
    <String>[
      'Aria',
      'Indica Vista',
      'Indigo Manza',
      'Safari',
      'Other',
    ],
    <String>[],
  ),
  tesla(
    'Tesla',
    'tesla',
    <String>[
      'Model 3',
      'Model S',
      'Model X',
      'Model Y',
      'Roadster',
      'Cybertruck',
      'Model 3',
      'Model S',
      'Semi',
      'Other',
    ],
    <String>[],
  ),
  toyota(
    'Toyota',
    'toyota',
    <String>[
      'Allion',
      'Alphard',
      'Aurion',
      'Auris',
      'Avensis',
      'Aygo',
      'Blade',
      'Camry',
      'Corolla',
      'Corolla Altis',
      'Corolla Verso',
      'Dyna 150',
      'Estima',
      'Fortuner',
      'GT86',
      'HiAce',
      'Hilux',
      'iQ',
      'Land Cruiser',
      'Land Cruiser Prado',
      'Mark X',
      'Matrix',
      'Premio',
      'Prius',
      'Ractis',
      'Rav4',
      'Tacoma',
      'Tundra',
      'Urban Cruiser',
      'Verso',
      'Verso S',
      'Vios',
      'Vitz',
      'Wish',
      'Yaris',
      'Yaris Verso',
      '4Runner',
      'Alphard',
      'Auris',
      'Avalon',
      'Avensis',
      'Avensis Verso',
      'Aygo',
      'Aygo X',
      'BZ4X',
      'C+pod',
      'C-HR',
      'Caldina',
      'Camry',
      'Celica',
      'Corolla',
      'Corolla Cross',
      'Corolla Verso',
      'Crown',
      'FJ Cruiser',
      'Fortuner',
      'GT 86',
      'Harrier',
      'Hiace',
      'Highlander',
      'Hilux',
      'iQ',
      'ist',
      'Land Cruiser',
      'Land Cruiser Prado',
      'Mark II',
      'Mirai',
      'MR2',
      'Picnic',
      'Previa',
      'Prius',
      'Prius Prime',
      'RAV4',
      'Sequoia',
      'Sienna',
      'Supra',
      'Tacoma',
      'Tundra',
      'Venza',
      'Verso',
      'Vitz',
      'Wish',
      'Yaris',
      'Yaris Verso',
      'Other',
    ],
    <String>[],
  ),
  troller('Troller', 'troller', <String>['T4', 'Other'], <String>[]), // NEW
  uaz(
    'UAZ',
    'uaz',
    <String>[
      '3153 Gusar',
      '3159 Bars',
      '3160',
      '3162 Simbir',
      'Buhanka',
      'Patriot Sport',
      'Pickup',
      'Profi',
      'ÐŸÐ°Ñ‚Ñ€Ð¸Ð¾Ñ‚',
      'Ð¥Ð°Ð½Ñ‚ÐµÑ€',
      'Other',
    ],
    <String>[],
  ),
  vauxhall(
    'Vauxhall',
    'vauxhall',
    <String>[
      'Agila',
      'Astra',
      'Commodore VZ',
      'Corsa',
      'Meriva',
      'Signum',
      'Vectra',
      'VX220',
      'Zafira',
      'Other',
    ],
    <String>[],
  ),
  vaz(
    'Vaz',
    'vaz',
    <String>[
      '2101-2107',
      '2108',
      '2110',
      '2113',
      '4x4 Urban',
      'Granta',
      'Granta Cross',
      'Largus',
      'Largus Cross',
      'Niva Bronto',
      'Niva Legend',
      'Niva Travel',
      'Vesta Cross',
      'Vesta Sport',
      'Vesta SW',
      'XRay',
      'XRay Cross',
      'Ð’ÐµÑÑ‚Ð°',
      'ÐšÐ°Ð»Ð¸Ð½Ð°',
      'ÐÐ¸Ð²Ð° 4X4',
      'ÐžÐºÐ°',
      'ÐŸÑ€Ð¸Ð¾Ñ€Ð°',
      'Other',
    ],
    <String>[],
  ),
  volga('Volga', 'volga', <String>['Siber', 'Other'], <String>[]), // NEW
  volkswagen(
    'Volkswagen',
    'volkswagen',
    <String>[
      'Amarok',
      'Arteon',
      'Beetle',
      'Bora',
      'Caddy',
      'CC',
      'Crafter',
      'CrossGolf',
      'CrossPolo',
      'CrossTouran',
      'California',
      'City Jetta',
      'Eos',
      'Fox',
      'Gol',
      'Golf',
      'Golf Plus',
      'Jetta',
      'Kombi',
      'ID.3',
      'ID.4',
      'ID.4 X',
      'ID.5',
      'ID.6 Crozz',
      'ID.6 X',
      'ID.Buzz',
      'Jetta',
      'Lupo',
      'Lavida',
      'LT',
      'Lupo',
      'Magotan',
      'Multivan',
      'New Beetle',
      'Parati',
      'Passat',
      'Passat CC',
      'Phaeton',
      'Pointer',
      'Polo',
      'Polocross',
      'Rabbit',
      'Routan',
      'Sagitar',
      'Saveiro',
      'Scirocco',
      'Sharan',
      'Tiguan',
      'Touareg',
      'Touran',
      'Transporter',
      'Vento',
      'Voyage',
      'T-Cross',
      'T-Roc',
      'Taigo',
      'Taos',
      'Tayron',
      'Teramont',
      'Teramont X',
      'Tiguan',
      'Tiguan X',
      'Touareg',
      'Touran',
      'Transporter',
      'Up',
      'Other',
    ],
    <String>[],
  ),
  volvo(
    'Volvo',
    'volvo',
    <String>[
      'C30',
      'S40',
      'S60',
      'C70',
      'S80',
      'V40',
      'V50',
      'V60',
      'V70',
      'Xc60',
      'Xc70',
      'Xc90',
      'C30',
      'C40',
      'C70',
      'C70 Convertible',
      'C70 Coupe',
      'EX30',
      'EX90',
      'S40',
      'S60',
      'S70',
      'S80',
      'S90',
      'V40',
      'V50',
      'V60',
      'V70',
      'V90',
      'XC40',
      'XC60',
      'XC70',
      'XC90',
      'Other',
    ],
    <String>[],
  ),
  yale('Yale', 'yale', <String>['Forklift', 'Other'], <String>[]), // NEW
  other('Other', 'other', <String>['Other'], <String>[]);

  const BrandType(this.title, this.json, this._models, this.filters);
  final String title;
  final String json;
  final List<String> _models;
  final List<String> filters;

  List<String> get models => _models.toSet().toList();

  static List<BrandType> get searchableBrands => BrandType.values;
  
  static List<BrandType> get makers => BrandType.values
      .where((BrandType e) => e != BrandType.all && e != BrandType.other)
      .toSet()
      .toList();

  static BrandType fromMap(String? value) {
    if (value == null) {
      return BrandType.other;
    }
    return BrandType.values.firstWhere(
      (BrandType e) => e.json == value,
      orElse: () => BrandType.other,
    );
  }
}
